module Constants {
		'use strict';

		export let Strings = {
				titles: {
						register: 'Registreren',
						welcome: 'Welkom',
						home: 'Reparatie - App',
						info: 'Info - pagina',
						error: 'Foutmelding',
						wizard: 'Reparatieverzoek',
						overview: 'Overzicht',
						success: 'Success',
						appointment: 'Reparatie aanvraag'
				},
				form: {
						personalInfo: 'Persoonsgegevens',
						address: 'Adres',
						validate: 'Versturen',
						skip: 'Overslaan'
				},
				menu: {
						repairRequest: 'Reparatieverzoek',
						byPhone: 'Telefonisch',
						withApp: 'Nieuwe reparatie aanvraag',
						rushRepair: 'Spoedreparatie',
						myAccount: 'Mijn account',
						myData: 'Mijn gegevens',
						myRepairs: 'Mijn reparatie aanvragen',
						callDirectly: 'Bel direct voor:',
						noHeating: 'Geen verwarming',
						glassDamage: 'Glasschade',
						elevatorMalfunction: 'Lift werkt niet'
				},
				extra: {
						outsideOfficeHours: '(ook buiten kantooruren)',
						byPhone: '(telefonisch)',
						firmRomijnders: '(firma Romijnders)',
						firmSeuren: '(firma Seuren)',
						firmKone: '(firma Kone)'
				},
				errors: {
						registrationNetwork: 'Er is iets misgegaan bij het valideren van uw gegevens. Controleer uw verbinding en probeer het opnieuw.',
						registrationDatabase: 'Er is iets misgegaan bij het  aanmaken van uw account. Probeer het later opnieuw.',
						noRegistration: 'U heeft zich nog niet geregistreerd, u moet eerst uw gegevens opgeven.',
						noTimesReceived: 'Er is iets misgegaan bij het ophalen van de beschikbare tijden. Controleer uw verbinding en probeer het opnieuw',
						noTimesAvailable: 'Op deze datum zijn geen tijden beschikbaar, probeer een andere datum',
						noDateTime: 'U moet een datum en tijd kiezen voor uw reparatieverzoek.',
						appointmentNetwork: 'Er is iets misgegaan bij het versturen van uw reparatieverzoek. Controleer uw verbinding en probeer het opnieuw',
						appointmentDatabase: 'Er is iets misgegaan bij het toevoegen van uw reparatieverzoek aan het overzicht.',
						overviewNetwork: 'Er is iets misgegaan bij het opvragen van uw reparatieverzoeken. Controleer uw verbinding en probeer het opnieuw',
						overviewDatabase: 'Er is iets misgegaan bij het opvragen van uw reparatieverzoeken.',
						cancelNetwork: 'Er is iets misgegaan bij het annuleren van uw reparatieverzoek. Controleer uw verbinding en probeer het opnieuw',
						cancelDatabase: 'Er is iets misgegaan bij het annuleren van uw reparatieverzoek.',
						noPhone: 'U moet een telefoonnummer invoeren'
				},
				messages: {
						loading: 'Uw gegevens worden geladen...',
						welcome: 'Met deze App kunt u eenvoudig en direct een reparatieverzoek of servicemelding indienen via ons online meldpunt. Daarnaast krijgt u, in veel gevallen, toegang tot onze digitale agenda zodat uzelf een afspraak kunt plannen wanneer u dat uitkomt.',
						continue: 'Doorgaan',
						appointmentOptions: 'Wat wilt u met deze reparatie aanvraag doen?'
				},
				buttons: {
						cancel: 'Afzeggen',
						close: 'Sluiten',
						back: 'Terug',
						goHome: 'Terug naar het hoofdmenu'
				},
				registration: {
						firstName: 'Voornaam',
						surname: 'Achternaam',
						phone: 'Telefoonnummer',
						email: 'Emailadres',
						street: 'Straat',
						houseNumber: 'Huisnummer',
						zipcode: 'Postcode',
						city: 'Plaats'
				},
				info: {
						aboutTheApp: {
								title: 'Werkwijze App',
								content: 'Met behulp van een eenvoudig menu op uw smartphone kunt u aangeven waar uw reparatieverzoek over gaat. Vervolgens kunt u extra informatie en/of een foto toevoegen aan uw verzoek. Indien mogelijk plant uzelf onze reparatie- en onderhoudsmedewerker in. U krijgt per e-mail een bevestiging met het door u vastgelegde tijdstip of wanneer direct plannen niet mogelijk is de mededeling dat u binnen twee werkdagen wordt teruggebeld. In sommige gevallen kunt u meteen een (nood)nummer bellen.'
						},
						howDoesItWork: {
								title: 'Reparatie- en onderhoudsapplicatie',
								content: 'Deze App is ontwikkeld op initiatief van Van Schaik Aannemingsbedrijf.'
						}
				},
				appointment: {
						pickDate: 'Datum kiezen',
						addPhoto: 'Foto toevoegen',
						notes: 'Opmerkingen',
						confirm: 'Bevestigen',
						submit: 'Verzenden',
						toBePlanned: 'Moet nog ingepland worden',
						notPlannable: 'Niet automatisch inplanbaar',
						none: 'Er zijn geen reparatieverzoeken'
				},
				phone: {
						elevatorMalfunction: 'Contact opnemen met Kone 0900-22255566',
						glass: 'Voor glas beschadigingen kunt u contact op nemen met Seuren 024-3231010',
						serviceElectrics: 'Geen elektra in de woning 0800-9009',
						serviceGas: 'Geen gas in de wonining 0800-9009',
						serviceWater: 'Geen water in de woning 0800-0359',
						serviceSewer: 'Verstopping',
						serviceHeating: 'Geen verwarming in de woning 024-6488222', 
						call: 'Bellen'
				},
				success: {
						intro: 'Geachte heer/mevrouw,',
						couldBePlanned: {
								title: 'Afspraakbevestiging',
								message: 'Uw reparatieverzoek met referentienummer %{referenceCode} is in goede orde ontvangen. Onze reparatie- en onderhoudsmedewerker komt op %{date} rond %{startTime} bij u langs. Bent u onverhoopt verhinderd op dit tijdstip geef dit dan tijdig door via de App (wijzigen reparatieverzoek, tot twee dagen voor geplande datum) of telefonisch op nummer 024-3817810.',
						},
						couldNotBePlanned: {
								title: 'Terugbelverzoek',
								message: 'Uw reparatieverzoek met referentienummer %{referenceCode} is in goede orde ontvangen. Onze reparatie- en onderhoudsmedewerker neemt binnen twee werkdagen contact met u op om een afspraak te maken. Voor vragen kunt u altijd bellen met 024-3817810.'
						},
						thanks: 'Hartelijk dank voor het gebruik van deze App.',
						greetings: 'Met vriendelijke groet,',
						owner: 'Afdeling reparatie en onderhoud'
				},
				wizard: {
						general: 'Algemene ruimte',
						inside: 'Binnen de woning',
						outside: 'Buiten de woning',
						around: 'Rondom de woning',
						entrance: 'Entree/hal',
						corridor: 'Galerij/gang/trap',
						basement: 'Kelder',
						elevator: 'Lift',
						garage: 'Parkeergarage',
						services: 'Voorzieningen',
						livingRoom: 'Woonkamer',
						kitchen: 'Keuken',
						bedroom: 'Slaapkamer',
						attic: 'Zolder',
						bathroom: 'Badkamer',
						toilet: 'Toilet',
						hallway: 'Gang/hal/trap',
						balcony: 'Balkon',
						flatRoof: 'Plat dak',
						slantedRoof: 'Schuin dak',
						facade: 'Gevel',
						generalStorage: 'Berging (algemeen)',
						privateStorage: 'Berging (eigen)',
						street: 'Pad/straat',
						parking: 'Parkeerplaats',
						generalShed: 'Schuur/garage (algemeen)',
						privateShed: 'Schuur/garage (eigen)',
						generalGarden: 'Tuin (algemeen)',
						privateGarden: 'Tuin (eigen)',
						other: 'Anders',
						bell: 'Bel / Deuropener / Intercom',
						mailBox: 'Brievenbus / Postkast / Papierbak',
						generalDoor: 'Algemene toegangsdeur',
						privateDoor: 'Eigen voordeur',
						extraKeys: 'Extra sleutels',
						renterBillSub: '(rekening huurder)',
						ownResponsibilitySub: '(door huurder)',
						lighting: 'Elektra / Verlichting',
						window: 'Kozijn / Raam',
						glass: 'Glas',
						nameTags: 'Naamplaatjes',
						nameTagHolders: 'Naamplaathouders',
						nameTagHoldersSub: '(alleen bij etagewoningen)', 
						pests: 'Ongedierte',
						pestsSub: '(gemeenschappelijke ruimtes rekening WBSG)', 
						walls: 'Plafond / Vloer / Wand',
						ventilation: 'Ventilatie',
						cleaning: 'Schoonmaak',
						railing: 'Balustrade / Hekwerk / Leuning',
						door: 'Deur',
						drainpipe: 'Regenpijp',
						corridorCleaningSub: '(galerij is voor huurder)',
						stairs: 'Trap',
						waterMeter: 'Watermeter',
						meterBox: 'Meterkast',
						basementRailing: 'Leuning',
						elevatorMalfunction: 'Lift werkt niet',
						elevatorDoor: 'Liftdeur',
						garageDoor: 'Garagedeur',
						parkingBarrier: 'Parkeerbeugel',
						sewer: 'Riool',
						barrier: 'Slagboom',
						water: 'Water',
						electrics: 'Elektra',
						provider: 'UPC/KPN',
						providerSub: '(wanneer u geen telefoon/kabel/internet ontvangt kunt u contact opnemen met u provider)',
						geyser: 'Geiser',
						kitchenAppliances: 'Keukenapparatuur',
						kitchenCounter: 'Keukenblok',
						drain: 'Riool / Afvoer',
						heating: 'Verwarming',
						faucet: 'Water / Kraan',
						kitchenGas: 'Gas / Gaskraan',
						roofWindow: 'Dakraam',
						sink: 'Wastafel',
						gas: 'Gas',
						vlizo: 'Trap / Vlizo',
						boiler: 'Ketel',
						bath: 'Bad',
						shower: 'Douche',
						showerDrain: 'Riool / Afvoer / Doucheput',
						washingMachine: 'Wasmachine',
						pipes: 'Waterleiding',
						toiletBowl: 'Toiletpot / Stortbak',
						toiletSeat: 'WC bril',
						toiletPaperHolder: 'Toiletrolhouder',
						hallwayElectrics: 'Elektra / Meterkast',
						mirror: 'Spiegel',
						soapTray: 'Zeepbakje',
						frontDoor: 'Voordeur',
						smokeAlarm: 'Rookmelders',
						balconySeparation: 'Balkonafscheiding',
						balconyCabinet: 'Balkonkast',
						outsideFloor: 'Plafond / Vloer',
						roof: 'Dak',
						gutter: 'Dakgoot',
						eaves: 'Dakrand',
						chimney: 'Schoorsteen',
						dormer: 'Dakkapel',
						outsideWall: 'Buitenmuur',
						porch: 'Portiek',
						outsideDoor: 'Buitendeur',
						manhole: 'Put / Riool',
						scooterCabinet: 'Kast scootmobiel',
						pavement: 'Bestrating',
						vegetation: 'Begroeiing',
						well: 'Put',
						fence: 'Schutting / Tuinmuur',
						lawn: 'Grasveld',
						gate: 'Toegangshek',
						shedOutsideWall: 'Buitenmuur',
						shedDoor: 'Garagedeur',
						gardenGate: 'Hek / Poort',
						playset: 'Speeltoestel',
						screen: 'Scherm / Schutting',
						gardenWall: 'Tuinmuur',
						frontDoorBell: 'Voordeurbel',
						doorOpener: 'Deuropener',
						interphone: 'Intercom',
						lock: 'Slot werkt niet',
						letterFlap: 'Brievenbusklep',
						mailBoxDoor: 'Deurtje',
						cylinder: 'Cilinder',
						cylinderSub: '(bij verlies, buitensluiting: kosten huurder)',
						hinges: 'Scharnieren',
						doorOpening: 'Deur gaat niet meer open of dicht',
						doorClosing: 'Sluit slecht/niet',
						doorDamage: 'Deur beschadigd',
						closer: 'Deurdranger',
						windowClosing: 'Raam sluit niet',
						windowLocks: 'Hang- en sluitwerk doet het niet',
						windowDamage: 'Kozijn/raam beschadigd',
						windowsillDamage: 'Vensterbank beschadigd',
						ceilingLeak: 'Lekkage plafond',
						ceilingDamage: 'Plafond beschadigd',
						floorDamage: 'Vloer beschadigd',
						floorTileDamage: 'Vloertegels beschadigd',
						wallDamage: 'Wand beschadigd',
						wallTileDamage: 'Wandtegels beschadigd',
						wallDirty: 'Wanden bevuild',
						wallGraffiti: 'Graffiti op de wanden',
						wallPainting: 'Schilderen, behangen en kleine reparatie stucwerk',
						bathroomWallPainting: 'Schilderen en kleine reparatie stucwerk',
						railingDamage: 'Leuning beschadigd',
						stairsDamage: 'Trap beschadigd',
						groundFault: 'Aardlek slaat er steeds uit',
						groundFaultSub: '(met spoed contact opnemen)',
						sewerDamage: 'Riool beschadigd',
						elevatorDoorClosing: 'Lift duer sluit niet / blijft open',
						leaking: 'Lekt water',
						noLongerLockable: 'Is niet meer afsluitbaar',
						parkingBarrierUpDown: 'Beugel gaat niet meer omhoog of omlaag',
						barrierOpening: 'Slagboom gaat niet meer open of dicht',
						barrierDamage: 'Slagboom beschadigd',
						waterDrain: 'Water loopt niet weg',
						waterLeak: 'Lekkage',
						plugMalfunction: 'Stopcontact doet het niet',
						lightSwitchMalfunction: 'Lightschakelaar doet het niet',
						lightingMalfunction: 'Verlichting doet het niet',
						ventMalfunction: 'Ventilatie rooster werkt niet',
						ventControl: 'Ventilatie rooster niet bedienbaar',
						ventDefect: 'Mechanische afzuiging defect',
						heatingMalfunction: 'Radiator wordt niet warm',
						heatingMalfunctionSub: '(radiator bijvullen en ontluchten, door huurder)',
						thermostatMalfunction: 'thermostatMalfunction',
						geyserMalfunction: 'Water wordt niet warm',
						cookerDefect: 'Kookplaat defect',
						ovenDefect: 'Oven defect', 
						hoodDefect: 'Afzuigkap defect',
						dishwasherDefect: 'Vaatwasser defect',
						drawerClosing: 'Lade of kastje sluit niet meer',
						drawerDamage: 'Lade kapot',
						lockerDamage: 'Kastje kapot',
						leafDamage: 'Blad kapot',
						faucetLeak: 'Kraan lekt',
						knobsMalfunction: 'Draai knoppen werken niet',
						faucetLoose: 'Kraan zit los',
						knobMalfunction: 'Draai knop werkt niet meer',
						hose: 'Gas slang',
						roofWindowClosing: 'Dakraam sluit niet',
						roofWindowDamage: 'Dakraam beschadigd',
						sinkDamage: 'Wastafel beschadigd',
						sinkleak: 'Wastafel lekt',
						siphonLeak: 'Sifon lekt',
						vlizoMalfunction: 'Vlizotrap werkt niet',
						vlizoDamage: 'Vlizotrap beschadigd',
						boilerMalfunction: 'Ketel defect',
						boilerRefill: 'Ketel bijvullen en radiatoren ontluchten',
						washingMachineDefect: 'Wasmachine defect',
						washingMachineDamage: 'Wasmachine beschadigd',
						bathFaucetLeak: 'Badkraan lekt',
						bathFaucetDefect: 'Badkraan defect',
						bathDamage: 'Bad beschadigd',
						showerFaucetLeak: 'Douchekraan lekt',
						showerFaucetDefect: 'Douchekraan defect',
						showerPoleDefect: 'Glijstang defect',
						showerheadLeak: 'Douchekop lekt',
						showerheadDefect: 'Douchekop defect', 
						showerHoseLeak: 'Doucheslang lekt',
						showerHoseDefect: 'Doucheslang defect',
						showerDrainDamage: 'Doucheputje beschadigd',
						pipeLeak: 'Waterleiding lekt',
						pipeAffected: 'Waterleiding aangetast',
						toiletBowlLeak: 'Toiletpot/stortbak lekt',
						cisternSlow: 'Stortbak loopt langzaam vol',
						toiletBowlDamage: 'Toiletpot/stortbak beschadigd',
						toiletFaucetLeak: 'Toilet kraan lekt',
						toiletFaucetClosing: 'Toilet kraan is niet meer afsluitbaar',
						mirrorDamage: 'Spiegel beschadigd',
						mirrorWorn: 'Spiegel verweerd',
						mirrorLoose: 'Spiegel hangt los',
						soapTrayDamage: 'Zeepbakje beschadigd',
						soapTrayLoose: 'Zeepbakje hangt los',
						smokeAlarmSignal: 'Rookmelder blijft signaal geven',
						smokeAlarmBattery: 'Batterij vervangen',
						smokeAlarmBatterySub: '(huurder zelf verantwoordelijk)',
						damaged: 'Beschadigd',
						rusted: 'Verroest',
						roofLeak: 'Dak lekkage',
						roofDamage: 'Dak beschadigd',
						gutterDamage: 'Dakgoot beschadigd',
						gutterLoose: 'Dakgoot hangt los',
						gutterBlocked: 'Dakgoot verstopt',
						gutterCleaning: 'Schoonhouden dakgoot',
						eavesDamage: 'Dakrand beschadigd',
						eavesLoose: 'Dakrand hangt los',
						chimneyDamage: 'Schoorsteen beschadigd',
						leadLoose: 'Lood hangt los',
						chimneyLoose: 'Schoorsteen pot staat los',
						roofTileLoose: 'Dakpan list los',
						roofTileLost: 'Dakpan weg gewaaid',
						roofWater: 'Dak staat vol water',
						fasciaLoose: 'Boeiboord hangt los',
						jointingLoose: 'Voegwerk laat los',
						brickLoose: 'Metselsteen zit los',
						manholeBlocked: 'Put/riool verstopt',
						cabinetDamage: 'Kast beschadigd',
						pavementLoose: 'Bestrating ligt los',
						pavementDamage: 'Bestrating beschadigd',
						vegetationBlown: 'Begroeiing is omgewaaid',
						vegetationGrown: 'Begroeiing is buiten proportie gegroeid',
						wellBlocked: 'Put is verstopt',
						brickWallDamage: 'Gemetselde muur is beschadigd',
						lawnGarbage: 'Afval op grasveld achtergelaten',
						gateClosing: 'Toegangshek gaat niet meer open of dicht',
						gateDamage: 'Toegangshek beschadigd',
						doorUpDown: 'Deur gaat niet meer omhoog of omlaag',
						privateWaterSub: '(huurder is zelf verantwoordelijk voor het afsluiten van de buitenkraan i.v.m. vorst)',
						playsetDamage: 'Speeltoestel beschadigd',
						playsetDirty: 'Speeltoestel bevuild',
						blockage: 'Water loopt niet weg',
						blockageSub: '(verstopping)',
						drainSmell: 'Afvoer stinkt',
						drainpipeDamage: 'Regenpijp beschadigd',
						allLights: 'Alle lampen doen het niet',
						singleLight: 'Één lamp doet het niet. Waar?....',
						cleaningSkipped: 'Schoonmaak niet uitgevoerd',
						garbageLeft: 'Afval achter gelaten'
				},
				weekDays: ['Zo', 'Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za'],
				months: ['Jan', 'Feb', 'Mrt', 'Apr', 'Mei', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec']
		};
};
